name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.channel }}
    - env:
        TARGET: ${{ matrix.target }}
        CHANNEL: ${{ matrix.channel }}
        FEATURES: ${{ matrix.features }}
        OP: build
      run: sh ci/run.sh
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, riscv64gc-unknown-linux-gnu]
        channel: [ 1.85.0, stable ]
        features: [ "fs,mmap,use-syscall", "fs,mmap,use-libc", "version", "log" ]

  test-rela:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.channel }}
    - env:
        TARGET: ${{ matrix.target }}
        CHANNEL: ${{ matrix.channel }}
        FEATURES: ${{ matrix.features }}
        OP: test
      run: sh ci/run.sh
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, riscv64gc-unknown-linux-gnu]
        channel: [ 1.85.0, stable ]
        features: [ "fs,mmap,use-syscall,lazy", "fs,mmap,use-libc,lazy" ]

  test-rel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.channel }}
    - env:
       TARGET: ${{ matrix.target }}
       CHANNEL: ${{ matrix.channel }}
       FEATURES: ${{ matrix.features }}
       OP: test
      run: sh ci/run.sh
    strategy:
      matrix:
         target: [ i586-unknown-linux-gnu, arm-unknown-linux-gnueabihf]
         channel: [ 1.85.0, stable ]
         features: [ "fs,mmap,use-syscall,rel,lazy", "fs,mmap,use-libc,rel,lazy" ]

  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.channel }}
    - env:
        TARGET: ${{ matrix.target }}
        CHANNEL: ${{ matrix.channel }}
        FEATURES: ${{ matrix.features }}
        OP: bench
      run: sh ci/run.sh
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu ]
        channel: [ stable ]
        features: [ "fs,mmap,use-syscall,lazy", "fs,mmap,use-libc,lazy" ]
